### ISSUE TITLE
Add null pointer protections.

### ISSUE THREAD

**Issue by pvc1989** [AdhocMan/gtest_mpi#2]
The pointer returned by [`getenv("TERM")`](https://github.com/AdhocMan/gtest_mpi/blob/d42a909032add3d6ab7b918926790110d48021a3/include/gtest_mpi/gtest_mpi_internal.hpp#L135C33-L135C33) would be `nullptr` if the environment variable is not found. This pointer is passed to [`CStringEquals`](https://github.com/AdhocMan/gtest_mpi/blob/d42a909032add3d6ab7b918926790110d48021a3/include/gtest_mpi/gtest_mpi_internal.hpp#L115), which just passes it to [`std::strcmp`](https://en.cppreference.com/w/cpp/string/byte/strcmp), whose behavior is undefined (possibly a segmentation fault) if either of its input pointers is a `nullptr`.
The fix is quite easy, actually. One way is to add null pointer protections in `CStringEquals`, just like what they did in [`gtest.cc`](https://github.com/google/googletest/blob/dddb219c3eb96d7f9200f09b0a381f016e6b4562/googletest/src/gtest.cc#L1225).

**Comment by AdhocMan** [comment]
Thanks for the suggestion.
It's now included with 950ecf8 in v1.1.1
